---
alm:
  conn: {
    host: '161.131.197.134',
    port: '8080',
    domain: 'BCI_AGILE',
    project: 'Viajes',
    user: '',
    pass: ''}
  tests: [{tag: 'prueba', test-id: '603', testset-id: '104'}] 
